services:
  jupyter_ml:
    build: ./docker/jupyter/
    volumes:
      - .:/home/jovyan/work
    ports:
      - "8888:8888"
  postgres_ml:
    build: ./docker/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
volumes:
  postgres_data:
    
